
preprocessing:
  target_column: Exited
  iqr_multiplier: 1.5
  strategy: any
  max_iter: 10
  verbose: true
  save_combined: data/processed/combined_data.csv
  save_clean: data/processed/combined_data_clean.csv

feature_engineering:
  enable: true
  apply_all_features: true
  custom_features: []

feature_selection:
  enable: true
  method: 'mutual_info'
  k: 20

feature_reduction:
  enable: false

paths:
  combine_sources:
    - data/raw/train.csv
    - data/raw/Churn_Modelling.csv
  test_path: data/raw/test.csv
  artifacts_dir: saved_models

split:
  test_size: 0.2
  random_state: 42

imbalance:
  methods: ['smote', 'adasyn', 'smote_tomek', 'smote_enn'] 
  sampling_strategy: auto

models:
  xgboost:
    train: true
    params:
      n_estimators: 500
      learning_rate: 0.05
      max_depth: 6
      subsample: 0.9
      colsample_bytree: 0.8
      reg_lambda: 1.0
      random_state: 42
      n_jobs: -1
      eval_metric: logloss
  lightgbm:
    train: true
    params:
      n_estimators: 700
      learning_rate: 0.03
      max_depth: -1
      subsample: 0.9
      colsample_bytree: 0.8
      reg_lambda: 1.0
      random_state: 42
  catboost:
    train: true
    params:
      iterations: 600
      learning_rate: 0.05
      depth: 6
      l2_leaf_reg: 3.0
      random_state: 42
      verbose: 0

metrics:
  validation: ['Accuracy', 'F1', 'Precision', 'Recall', 'ROC_AUC', 'PR_AUC']
  test: ['Accuracy', 'F1', 'Precision', 'Recall', 'ROC_AUC', 'PR_AUC']
